"""GK_base

Revision ID: 7e54e43d3a09
Revises: d1d1011c7e2b
Create Date: 2025-05-24 21:37:20.119513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e54e43d3a09'
down_revision: Union[str, None] = 'd1d1011c7e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gk_users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('gk_users', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gk_users', 'token')
    op.drop_column('gk_users', 'password')
    # ### end Alembic commands ###
