"""GK_base

Revision ID: a44b966a04ed
Revises: caea602a7b53
Create Date: 2025-05-24 16:23:18.639498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a44b966a04ed'
down_revision: Union[str, None] = 'caea602a7b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'prefix',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'display',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('promo_services', 'active',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('promo_services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('promo_services', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('promo_services', 'denomination',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('promo_services', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'icon_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'service_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('services', 'service_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'icon_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('promo_services', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('promo_services', 'denomination',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('promo_services', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('promo_services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('promo_services', 'active',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'display',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'prefix',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
