"""GK_base

Revision ID: caea602a7b53
Revises: 3c49c4652994
Create Date: 2025-05-24 16:20:59.414275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caea602a7b53'
down_revision: Union[str, None] = '3c49c4652994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_gk_id'), table_name='cities')
    op.create_index(op.f('ix_cities_gk_id'), 'cities', ['gk_id'], unique=False)
    op.drop_index(op.f('ix_medias_gk_id'), table_name='medias')
    op.create_index(op.f('ix_medias_gk_id'), 'medias', ['gk_id'], unique=False)
    op.drop_index(op.f('ix_products_gk_id'), table_name='products')
    op.create_index(op.f('ix_products_gk_id'), 'products', ['gk_id'], unique=False)
    op.drop_index(op.f('ix_promo_services_gk_id'), table_name='promo_services')
    op.create_index(op.f('ix_promo_services_gk_id'), 'promo_services', ['gk_id'], unique=False)
    op.drop_index(op.f('ix_services_gk_id'), table_name='services')
    op.create_index(op.f('ix_services_gk_id'), 'services', ['gk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_gk_id'), table_name='services')
    op.create_index(op.f('ix_services_gk_id'), 'services', ['gk_id'], unique=True)
    op.drop_index(op.f('ix_promo_services_gk_id'), table_name='promo_services')
    op.create_index(op.f('ix_promo_services_gk_id'), 'promo_services', ['gk_id'], unique=True)
    op.drop_index(op.f('ix_products_gk_id'), table_name='products')
    op.create_index(op.f('ix_products_gk_id'), 'products', ['gk_id'], unique=True)
    op.drop_index(op.f('ix_medias_gk_id'), table_name='medias')
    op.create_index(op.f('ix_medias_gk_id'), 'medias', ['gk_id'], unique=True)
    op.drop_index(op.f('ix_cities_gk_id'), table_name='cities')
    op.create_index(op.f('ix_cities_gk_id'), 'cities', ['gk_id'], unique=True)
    # ### end Alembic commands ###
