"""GK_base

Revision ID: d1d1011c7e2b
Revises: a44b966a04ed
Create Date: 2025-05-24 19:24:19.649934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d1011c7e2b'
down_revision: Union[str, None] = 'a44b966a04ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gk_users', sa.Column('user_uuid', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('gk_users', sa.Column('gk_user_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_gk_users_gk_user_id'), 'gk_users', ['gk_user_id'], unique=True)
    op.create_index(op.f('ix_gk_users_user_uuid'), 'gk_users', ['user_uuid'], unique=True)
    op.create_foreign_key(None, 'gk_users', 'users', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gk_users', type_='foreignkey')
    op.drop_index(op.f('ix_gk_users_user_uuid'), table_name='gk_users')
    op.drop_index(op.f('ix_gk_users_gk_user_id'), table_name='gk_users')
    op.drop_column('gk_users', 'gk_user_id')
    op.drop_column('gk_users', 'user_uuid')
    # ### end Alembic commands ###
